### ISSUE TITLE
Error after start: events.js:182

### ISSUE THREAD

**Issue by vingrad** [bamlab/generator-rn-toolbox#104]
Node version: 8

`? Name of your react-native project myproject

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Command failed: identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.

    at ChildProcess.onExit (/usr/local/lib/node_modules/generator-rn-toolbox/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)
`

**Comment by Almouro** [comment]
Hi @vingrad, what was the command you tried to run?
I assume you ran an `assets` command, can you also attach the image you were trying to use?
Thanks!

**Comment by Almouro** [comment]
Hi @vingrad, I'm closing this issue, since there was no activity for a while.
Feel free to reopen if you still have a problem!

**Comment by jesstice** [comment]
Hi @Almouro, I am having this same issue and I ran an `assets` command: ` yo rn-toolbox:assets --icon`. Should I create a new issue?

**Comment by Almouro** [comment]
Hi @jesstice, I can reopen this one :)

I'll ask the same questions: 
what was the command you tried to run?
I assume you ran an assets command, can you also attach the image you were trying to use?
Thanks!

**Comment by klakshman318** [comment]
**Command:**  
yo rn-toolbox:assets --icon random.png

**Error:**

`events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-forma
ns the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\Users\MyPC\AppData\Roaming\npm\nod
\gm\lib\command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.cp.emit (C:\Users\MyPC\AppData\Roaming\npm\node_mo
ss-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

**Comment by chinmaygit** [comment]
make sure you have installed _imagemagick_ on your system,
for mac: `brew install imagemagick`

**Comment by klakshman318** [comment]
for mac: `brew install imagemagic`k i know this, but I'm using windows and I did manage to install it using chocolatey. still, it's not working.! any solution you got for windows users??

**Comment by klakshman318** [comment]
never mind. I got it from here. 

[ Assets ](https://github.com/bamlab/generator-rn-toolbox/tree/master/generators/assets#troubleshooting)

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use @bam.tech/react-native-make

The new version does not depend on image magick being installed, so it should solve your issue 😉
