### ISSUE TITLE
[App CRASH] [SplashScreen generator] due to color.xml declaration

### ISSUE THREAD

**Issue by michel-p** [bamlab/generator-rn-toolbox#107]
On Investo Project, we encountered an issue after using the splashscreen generator : 

```
06-30 08:01:32.714  6645  6645 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.investo.debug:drawable/launch_screen_bitmap with resource ID #0x7f02003f
06-30 08:01:32.714  6645  6645 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_screen_bitmap.xml from drawable resource ID #0x7f02003f
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:771)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:525)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2577)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2627)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:433)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:424)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.Activity.setContentView(Activity.java:2434)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:114)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6679)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.investo.debug:color/splashBackground with resource ID #0x7f0c0037
06-30 08:01:32.714  6645  6645 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File rgb(60,147,239) from drawable resource ID #0x7f0c0037
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:858)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:388)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:267)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:196)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
06-30 08:01:32.714  6645  6645 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:771)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:525)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2577)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2627)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:433)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:424)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.Activity.setContentView(Activity.java:2434)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:114)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6679)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
06-30 08:01:32.717  6645  6645 E AndroidRuntime: Caused by: java.io.FileNotFoundException: rgba(0,0,0,0)
```

Our .psd file was at the recommended size and with a fixed background color.

In the file android/app/src/main/res/values/colors.xml there was a rgba color created by the generator :
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="splashBackground" type="color">rgba(0,0,0,0)</item>
</resources>
```

I fixed the app by editing it like this : 
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="splashBackground" type="color">#3c93ef</item>
</resources>
```

**Comment by Almouro** [comment]
Hi @michel-p,

Thanks for posting an issue here!

Can you attach the `psd` you were trying to use?

Thanks!

**Comment by brunoarueira** [comment]
It's not specific to psd, occurs with png too since both supports alpha channel! My solution is to get the rgba defined and convert to hex using an online tool.

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version uses creates a whole layout for the splash-screen making it easier to customize it, regarding the color issue, we don't compute it by default anymore but let you input yours. Hope it helps you with your issue 😉
