### ISSUE TITLE
"this most likely means the gm/convert binaries can't be found",attempting to change Icon

### ISSUE THREAD

**Issue by mr-bat** [bamlab/generator-rn-toolbox#117]
When I was using 'yo rn-toolbox:assets --icon ./images/mainIcon.png' to change the app's icon I encountered:

`events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "images/mainIcon.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/generator-rn-toolbox/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)`

**Comment by mr-bat** [comment]
solved my problem by 
`brew install imagemagick`
to any one who is using the command: take a look at https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/README.md first.

**Comment by youvita** [comment]
great it work for me. Mr. mr-bat thanks so much for your good solution.
