### ISSUE TITLE
Advanced Base Does Not Work

### ISSUE THREAD

**Issue by JimTheMan** [bamlab/generator-rn-toolbox#234]
I am trying to use advanced-base, but it totally breaks my app.

To reproduce:

1. create a react app.

```
react-native init my-app
```

2. Run advanced base generator

```
yo rn-toolbox:advanced-base
```

(say yes to all overwrite questions)

3. Start app locally

```
react-native run-ios
```

Result: app crashes with this output:

> error: bundling failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/babel-preset-react-native/index.js
    at createDescriptor (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/jim/Git-Projects/React-Native-With-A-Friend/WithFriend2/node_modules/@babel/core/lib/config/config-chain.js:120:22)

using:
node v10.16.0
react - 16.8.6
rn-toolbox - 3.1.0

**Comment by JimTheMan** [comment]
blumpkins
