### ISSUE TITLE
Error: Cannot find module 'universal-analytics'

### ISSUE THREAD

**Issue by sayem314** [bamlab/generator-rn-toolbox#240]
```
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/generator-rn-toolbox/analytics.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/generator-rn-toolbox/generators/assets/index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by cristian-milea** [comment]
i installed universal-analytics  globally as a temporary fix

`npm i -g universal-analytics`

**Comment by sayem314** [comment]
I did too! But this shouldn’t be the case!

**Comment by yleflour** [comment]
Hello, sorry for the inconvenience, I just released the fix in 3.13.1
I blindly forgot to include a package.json change in my commit

**Comment by sayem314** [comment]
I see you have added this on the new version but next time you should update with yarn and include lock file as well. Just a suggestion!

**Comment by yleflour** [comment]
> I see you have added this on the new version but next time you should update with yarn and include lock file as well. Just a suggestion!

It was already included in the yarn.lock but forgot to commit the package.json. It was a mistake due to the usage of semantic-release which I had to run locally.
