### ISSUE TITLE
Make fastlane generator works with cordova

### ISSUE THREAD

**Issue by Nhacsam** [bamlab/generator-rn-toolbox#31]
```
AssertionError: /Users/nicolasd/Projects/project/android/app/build.gradle doesn't exist
    at EditionInterface.module.exports [as read] (/Users/nicolasd/.nvm/versions/node/v6.2.0/lib/node_modules/generator-rn-toolbox/node_modules/mem-fs-editor/lib/actions/read.js:18:3)
    at FastlaneGenerator._extendGradle (/Users/nicolasd/.nvm/versions/node/v6.2.0/lib/node_modules/generator-rn-toolbox/generators/fastlane/index.js:125:26)
    at FastlaneGenerator.writing (/Users/nicolasd/.nvm/versions/node/v6.2.0/lib/node_modules/generator-rn-toolbox/generators/fastlane/index.js:111:10)
    at Object.<anonymous> (/Users/nicolasd/.nvm/versions/node/v6.2.0/lib/node_modules/generator-rn-toolbox/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/nicolasd/.nvm/versions/node/v6.2.0/lib/node_modules/generator-rn-toolbox/node_modules/run-async/index.js:26:25
    at /Users/nicolasd/.nvm/versions/node/v6.2.0/lib/node_modules/generator-rn-toolbox/node_modules/run-async/index.js:25:19
```

**Comment by yleflour** [comment]
@Nhacsam You should probably fork this to a repo like `cordova-toolbox`
