### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by chandu0101** [bamlab/generator-rn-toolbox#73]
`yo rn-toolbox:assets --icon icon.png`
```js
class ResourcesGenerator extends Base {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

```

**Comment by Almouro** [comment]
Hi @chandu0101, thanks for submitting an issue! :)

What version of Node are you using? **Node 6 or 7 is required** to use this generator.
Sorry if that wasn't clear, I just added everything that was needed in [here](https://github.com/bamlab/generator-rn-toolbox/tree/master/generators/assets#requirements)

**Comment by chandu0101** [comment]
ah 

```js
         v4.0.0
         v4.3.2
->       v5.9.1
         v6.9.1
         system

```

I don't know why its went back to 5.9.1 :s ,  thanks for reply  and i just ran the command , but i am getting following errors 

```js
RefsChildImages.xcassets: error: The app icon set named "AppIcon" did not have any applicable content.
/* com.apple.actool.document.warnings */
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][20x20][][][2x]: warning: AppIcon.appiconset/icon-20@2x.png is 24x40 but should be 40x40.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][20x20][][][1x]: warning: AppIcon.appiconset/icon-20@1x.png is 12x20 but should be 20x20.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][60x60][][][2x]: warning: AppIcon.appiconset/icon-60@2x.png is 73x120 but should be 120x120.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][50x50][][][2x]: warning: AppIcon.appiconset/icon-50@2x.png is 61x100 but should be 100x100.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][83.5x83.5][][][2x]: warning: AppIcon.appiconset/icon-83.5@2x.png is 102x167 but should be 167x167.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][50x50][][][1x]: warning: AppIcon.appiconset/icon-50@1x.png is 31x50 but should be 50x50.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][20x20][][][3x]: warning: AppIcon.appiconset/icon-20@3x.png is 37x60 but should be 60x60.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][57x57][][][2x]: warning: AppIcon.appiconset/icon-57@2x.png is 70x114 but should be 114x114.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][72x72][][][1x]: warning: AppIcon.appiconset/icon-72@1x.png is 44x72 but should be 72x72.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][40x40][][][2x]: warning: AppIcon.appiconset/icon-40@2x.png is 49x80 but should be 80x80.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][76x76][][][2x]: warning: AppIcon.appiconset/icon-76@2x.png is 93x152 but should be 152x152.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][57x57][][][1x]: warning: AppIcon.appiconset/icon-57@1x.png is 35x57 but should be 57x57.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][20x20][][][2x]: warning: AppIcon.appiconset/icon-20@2x.png is 24x40 but should be 40x40.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][60x60][][][3x]: warning: AppIcon.appiconset/icon-60@3x.png is 110x180 but should be 180x180.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][29x29][][][1x]: warning: AppIcon.appiconset/icon-29@1x.png is 18x29 but should be 29x29.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][76x76][][][1x]: warning: AppIcon.appiconset/icon-76@1x.png is 46x76 but should be 76x76.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][29x29][][][2x]: warning: AppIcon.appiconset/icon-29@2x.png is 35x58 but should be 58x58.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][40x40][][][3x]: warning: AppIcon.appiconset/icon-40@3x.png is 73x120 but should be 120x120.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][72x72][][][2x]: warning: AppIcon.appiconset/icon-72@2x.png is 88x144 but should be 144x144.
RefsChildImages.xcassets:./AppIcon.appiconset/[][ipad][40x40][][][1x]: warning: AppIcon.appiconset/icon-40@1x.png is 24x40 but should be 40x40.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][29x29][][][1x]: warning: AppIcon.appiconset/icon-29@1x.png is 18x29 but should be 29x29.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][29x29][][][3x]: warning: AppIcon.appiconset/icon-29@3x.png is 53x87 but should be 87x87.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][29x29][][][2x]: warning: AppIcon.appiconset/icon-29@2x.png is 35x58 but should be 58x58.
RefsChildImages.xcassets:./AppIcon.appiconset/[][iphone][40x40][][][2x]: warning: AppIcon.appiconset/icon-40@2x.png is 49x80 but should be 80x80.
/* com.apple.actool.compilation-results */
ios/build/Build/Intermediates/ZBNF.build/Debug-iphonesimulator/ZBNF.build/assetcatalog_generated_info.plist



** BUILD FAILED **
```

**Comment by Almouro** [comment]
We only support square images for assets generations, for now. (I added that in the README).
Did you try with a square image?

**Comment by chandu0101** [comment]
:( , i didn't  tried square image , its good to throw error if user supplier reactangle , anyway thanks for awesome tool :)
