### ISSUE TITLE
Error running yo rn-toolbox:assets --icon

### ISSUE THREAD

**Issue by corasan** [bamlab/generator-rn-toolbox#98]
When I run `yo rn-toolbox:assets --icon` I get this error:

```/usr/local/lib/node_modules/generator-rn-toolbox/generators/assets/index.js:7
class ResourcesGenerator extends Base {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.defineProperty.get [as rn-toolbox:assets] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:261:21)
```

**Comment by Almouro** [comment]
Hi @corasan, thanks for posting this issue!

You need node >= 6 installed (I strongly suggest using [NVM](https://github.com/creationix/nvm))
It is stated in the docs [here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/README.md#requirements), but maybe it wasn't clear enough :(

How do you think we could have made it clearer? :) Thanks!

**Comment by corasan** [comment]
My bad!! I have node 6 in my other computer, got confused and thought I had it on this one. Thank you.

It is clear enough in the docs tho.
